name: .NET Core

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.301
    - name: Install dependencies
      run: dotnet restore Samples/samples.csproj
    - name: Build
      run: dotnet build -warnAsError --configuration Release --no-restore Samples/samples.csproj
    - name: Test
      run: dotnet test --verbosity normal LoadBalancerTests/LoadBalancerTests.csproj.sln
    - name: Sample
      run: dotnet run Samples/samples.csproj.sln
